### ISSUE TITLE
Scala 2.13 release

### ISSUE THREAD

**Issue by Daenyth** [ChristopherDavenport/cormorant#145]
Just requesting a 2.13 release so I can get a codebase updated

**Comment by ChristopherDavenport** [comment]
Waiting on http4s release presently.

**Comment by Daenyth** [comment]
Bump on this - There's at least a milestone out, and cormorant-fs2 at the latest release depends on fs2 1.1.x, so it's incompatible with the latest http4s and fs2

**Comment by ChristopherDavenport** [comment]
Should be fixed now
