### ISSUE TITLE
Error message when csv header doesn't match case class fields is bad

### ISSUE THREAD

**Issue by Daenyth** [ChristopherDavenport/cormorant#32]
I tried importing a csv file without realizing the headers were wrong, and the error was just `io.chrisdavenport.cormorant.Error$DecodeFailure: null` with no description of what was wrong.

I'd prefer to get a message telling me the headers didn't match, or at least not `null`. My error handling code ended up having an NPE because I forgot messages could be null

**Comment by ChristopherDavenport** [comment]
Fixed by #33
