### ISSUE TITLE
Allow csv files to have trailing empty lines

### ISSUE THREAD

**Issue by Daenyth** [ChristopherDavenport/cormorant#34]
It's really common for incoming data to have a blank line at the end, so it would be nice if callers didn't need to explicitly trim that empty line.

I don't really care if it allows or disallows mid-file empty lines, but the trailing one is common IME.

**Comment by ChristopherDavenport** [comment]
So it currently seems to be an unfortunate ambiguity in the actual spec. As I've written it directly to the spec and it parses the last line as an empty string of a single column.

This is a fascinating ambiguity. If I automatically remove it what would the expected output by for some Optional[String] column

```
Column\r\n
\r\n
\r\n
```

How would you expect that to be parsed?

**Comment by Daenyth** [comment]
:(

I have no idea. If there's one column, there's no separator is there? In that case the file contents would be ambiguous. What if we restricted the trimming to multi-column CSVs? If the header defines two columns and you get `\r\n` or `\n`, then it's unambiguously a bad line.

**Comment by ChristopherDavenport** [comment]
Fixed by #47
