### ISSUE TITLE
Parser for BigDecimal returns error when spaces are around the number

### ISSUE THREAD

**Issue by Daenyth** [ChristopherDavenport/cormorant#55]
Parsing a column with `" 1.99 "` as a BigDecimal fails. This is overall reasonable behavior, but it does make it awkward working with data that might be supplied in an unclean way.

I'm pretty sure I can put an implicit into my code that will wrap the built-in parser for `BigDecimal` and just `.trim` the string, but is there a better way to handle it? Is this something the library should support?

**Comment by ChristopherDavenport** [comment]
That is not valid per the spec and I'd suggest that a custom `Read` be written for it that does the behavior you want.

**Comment by Daenyth** [comment]
That's what I thought - thanks
